id: IF92B2442
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T05:05:18+00:00'
last_modified: '2022-06-08T13:54:23.821927+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09683
  title: གསུང་ཐོར་བུ། སངས་སྤྲུལ་དཀོན་མཆོག་བསྟན་པའི་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CA6E:
      image_group_id: I00KG09722
      title: ''
      total_pages: 334
      order: 1
      base_file: CA6E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
