id: P010479
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:51:57.648132
source_metadata:
  id: bdr:W00KG09683
  title: གསུང་ཐོར་བུ། སངས་སྤྲུལ་དཀོན་མཆོག་བསྟན་པའི་རྒྱལ་མཚན།
  author: ''
  volumes:
    6ea4665375e747b1969af6dc7a3ffcc9:
      image_group_id: I00KG09722
      title: ''
      volume_number: 1
      total_pages: 334
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
